### ISSUE TITLE
issues#20 task table 關聯修正

### ISSUE THREAD

**Issue by chiehhhaa** [astrocamp/16th-Diswork#41]
參考：
![IMG_1702](https://github.com/astrocamp/16th-Diswork/assets/165154205/9e52977e-58d7-4b86-bbc1-62b503cab085)

**Comment by dali1756** [comment]
![S__15491099](https://github.com/astrocamp/16th-Diswork/assets/99263019/36c72719-8f5e-4d34-953d-b9e2c422fe05)
